// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW7Z9tQnPAPCaS1RLUM6p-IEUqqg-9_As',
    appId: '1:875840290982:web:ba747739ad29e115807467',
    messagingSenderId: '875840290982',
    projectId: 'college-e1a35',
    authDomain: 'college-e1a35.firebaseapp.com',
    storageBucket: 'college-e1a35.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjuI-B0yOEYQzYQaSbDao1tn7Adq_xG0U',
    appId: '1:875840290982:android:76d976e384b44688807467',
    messagingSenderId: '875840290982',
    projectId: 'college-e1a35',
    storageBucket: 'college-e1a35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmvmdpa-WsN18tDAdtkVjtuGDzJCk5t1k',
    appId: '1:875840290982:ios:0b3f9538ddabe738807467',
    messagingSenderId: '875840290982',
    projectId: 'college-e1a35',
    storageBucket: 'college-e1a35.firebasestorage.app',
    iosBundleId: 'com.example.college',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmvmdpa-WsN18tDAdtkVjtuGDzJCk5t1k',
    appId: '1:875840290982:ios:0b3f9538ddabe738807467',
    messagingSenderId: '875840290982',
    projectId: 'college-e1a35',
    storageBucket: 'college-e1a35.firebasestorage.app',
    iosBundleId: 'com.example.college',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW7Z9tQnPAPCaS1RLUM6p-IEUqqg-9_As',
    appId: '1:875840290982:web:33ffcd78da7fdbe4807467',
    messagingSenderId: '875840290982',
    projectId: 'college-e1a35',
    authDomain: 'college-e1a35.firebaseapp.com',
    storageBucket: 'college-e1a35.firebasestorage.app',
  );
}
